stages:
  - deploy

deploy:
  stage: deploy
  environment: production
  script:
    - rm -rf node_modules
    - npm install
    - npm run build
    - pm2 reload ecosystem.config.js --env production
  tags:
    - deploy
  only:
    - master