query {
  authoritySetInfo {
    leaders
      audits
      auditVersions {
        version
        count
      }
      leaderVersions {
        version
        count
      }
      identitiesNotFound
  }
}
