subscription {
  latestLoadTestChanged {
    _id
    start {
      user
      timestamp
    }
    end {
      user
      timestamp
    }
    type
    chainIds
    generatorConfig {
      ... on ConstantLoadConfig {
        eps
        entrySize
      }
    }
  }
}
