subscription {
  latestLoadTestChanged {
    _id
    start {
      user
      timestamp
    }
    end {
      user
      timestamp
    }
    type
    chainIds
    entrySizeRange {
      min
      max
    }
    agentsCount
    authoritySet {
      leaders
      audits
      auditVersions {
        version
        count
      }
      leaderVersions {
        version
        count
      }
    }
    generatorConfig {
      eps
      nbEntries
    }
  }
}
