query loadTestHistory($timestamp: Int, $pageSize: Int!) {
  loadTestHistory(timestamp: $timestamp, pageSize: $pageSize) {
    _id
    start {
      user
      timestamp
    }
    end {
      user
      timestamp
    }
    type
    chainIds
    agentsCount
    entrySizeRange {
      min
      max
    }
    authoritySet {
      mainVersion
    }
    generatorConfig {
      eps
      nbEntries
    }
  }
}
