subscription {
  loadTestChanged {
    id
    events {
      user
      type
      timestamp
    }
    generator {
      config {
        eps
        nbOfChains
        entrySize
      }
      data {
        ecAddress
      }
    }
  }
}
