query loadTestHistory($lastId: String, $pageSize: Int!) {
  loadTestHistory(id: $lastId, pageSize: $pageSize) {
    _id
    start {
      user
      timestamp
    }
    end {
      user
      timestamp
    }
    type
    chainIds
    authoritySet {
      mainVersion
    }
    generatorConfig {
      ... on ConstantLoadConfig {
        eps
      }
    }
  }
}
