query loadTest($id: String) {
  loadTest(id: $id) {
    _id
    start {
      user
      timestamp
    }
    end {
      user
      timestamp
    }
    type
    chainIds
    agentsCount
    entrySizeRange {
      min
      max
    }
    authoritySet {
      leaders
      audits
      auditVersions {
        version
        count
      }
      leaderVersions {
        version
        count
      }
    }
    generatorConfig {
      eps
      nbEntries
    }
  }
}
